### ISSUE TITLE
[Bug] Tries to delete non-existent Quilt Jar

### ISSUE THREAD

**Issue by CodeF53** [PacifistMC/Forgix#2]
Running the merge jars task through forgix 1.0, I get the following error:

```
> Task :mergeJars FAILED

Settings:
Forge: Yes
Fabric: Yes
Quilt: No
Group: net.cardinalboats
Merged Jar Name: cardinalboats_1.19_1.1.0.jar

total: 86398
total: 85365

Execution failed for task ':mergeJars'.
> Cannot invoke "java.io.File.delete()" because "this.quiltJar" is null

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mergeJars'.
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.delete()" because "this.quiltJar" is null
	at io.github.pacifistmc.forgix.Forgix.merge(Forgix.java:189)
	at io.github.pacifistmc.forgix.plugin.MergeJarsTask.mergeJars(MergeJarsTask.java:103)
```

[Full stacktrace](https://pastebin.com/XFhYY5NU)

It properly detects Quilt as not active in Architectury but still tries to do stuff with Quilt.

[Here is the project that gets this issue](https://github.com/CodeF53/CardinalIceBoats)

**Comment by Ran-helo** [comment]
Oops thanks for the fix!
